import { singleQuote } from '@tarojs/shared';

const DEFAULT_TRUE = '!0';
const DEFAULT_FALSE = '!1';
const DEFAULT_EMPTY_ARRAY = '[]';

// 同步版本：v1.11.7
// NOTE:
// 颜色，尺寸是通过 CSS variable 实现默认值的，不需要在这里做默认值的维护

/** VANT 所有组件及其有默认值的属性 */
export const COMPONENTS: Record<string, Record<string, any>> = {
  'van-button': {
    type: singleQuote('default'),
    size: singleQuote('normal'),
    'class-prefix': singleQuote('van-icon'),
    plain: DEFAULT_FALSE,
    block: DEFAULT_FALSE,
    round: DEFAULT_FALSE,
    square: DEFAULT_FALSE,
    disabled: DEFAULT_FALSE,
    hairline: DEFAULT_FALSE,
    loading: DEFAULT_FALSE,
    'loading-type': singleQuote('circular'),
    // 'loading-size': singleQuote('20px'),
    lang: singleQuote('en'),
    // 'send-message-title': singleQuote('当前标题'),
    // 'send-message-path': singleQuote('当前分享路径'),
    // 'send-message-img': singleQuote('截图'),
    'show-message-card': DEFAULT_FALSE
  },
  'van-cell-group': {
    inset: DEFAULT_FALSE,
    border: DEFAULT_TRUE,
  },
  'van-cell': {
    border: DEFAULT_TRUE,
    center: DEFAULT_FALSE,
    'link-type': singleQuote('navigateTo'),
    clickable: DEFAULT_FALSE,
    'is-link': DEFAULT_FALSE,
    required: DEFAULT_FALSE,
    'use-label-slot': DEFAULT_FALSE,
  },
  'van-cascader': {
    options: DEFAULT_EMPTY_ARRAY,
    placeholder: singleQuote('请选择'),
    swipeable: DEFAULT_FALSE,
    closeable: DEFAULT_TRUE,
    ellipsis: DEFAULT_TRUE,
    'show-header': DEFAULT_TRUE,
    'close-icon': singleQuote('cross'),
    'field-names': "{text:'text',value:'value',children:'children'}"
  },
  'van-icon': {
    dot: DEFAULT_FALSE,
    color: singleQuote('inherit'),
    size: singleQuote('inherit'),
    'class-prefix': singleQuote('van-icon'),
  },
  'van-image': {
    fit: singleQuote('fill'),
    radius: '0',
    round: DEFAULT_FALSE,
    webp: DEFAULT_FALSE,
    'lazy-load': DEFAULT_FALSE,
    'show-error': DEFAULT_TRUE,
    'show-loading': DEFAULT_TRUE,
    'use-error-slot': DEFAULT_FALSE,
    'use-loading-slot': DEFAULT_FALSE,
    'show-menu-by-longpress': DEFAULT_FALSE,
  },
  'van-popup': {
    show: DEFAULT_FALSE,
    'z-index': '100',
    overlay: DEFAULT_TRUE,
    position: singleQuote('center'),
    duration: '300',
    round: DEFAULT_FALSE,
    'close-on-click-overlay': DEFAULT_TRUE,
    closeable: DEFAULT_FALSE,
    'close-icon': singleQuote('cross'),
    'safe-area-inset-bottom': DEFAULT_TRUE,
    'safe-area-inset-top': DEFAULT_FALSE,
    'safe-area-tab-bar': DEFAULT_FALSE,
    'lock-scroll': DEFAULT_TRUE,
    'root-portal': DEFAULT_FALSE
  },
  'van-transition': {
    name: singleQuote('fade'),
    show: DEFAULT_TRUE,
    duration: '300',
  },
  'van-calendar': {
    type: singleQuote('single'),
    title: singleQuote('日期选择'),
    // color: singleQuote('#ee0a24'),
    'min-date': 'xs.today', // 今天
    'max-date': 'xs.datetime(xs.date(xs.year, xs.month + 6, xs.day))', // 六个月后
    // 'default-date': '今天',
    'row-height': '64',
    poppable: DEFAULT_TRUE,
    'show-mark': DEFAULT_TRUE,
    'show-title': DEFAULT_TRUE,
    'show-subtitle': DEFAULT_TRUE,
    'show-confirm': DEFAULT_TRUE,
    'confirm-text': singleQuote('确定'),
    'confirm-disabled-text': singleQuote('确定'),
    'first-day-of-week': '0',
    readonly: DEFAULT_FALSE,
    show: DEFAULT_FALSE,
    position: singleQuote('bottom'),
    round: DEFAULT_TRUE,
    'close-on-click-overlay': DEFAULT_TRUE,
    'safe-area-inset-bottom': DEFAULT_TRUE,
    // 'range-prompt': '选择天数不能超过 xx 天',
    'show-range-prompt': DEFAULT_TRUE,
    'allow-same-day': DEFAULT_FALSE,
    'min-range': '1'
  },
  'van-checkbox': {
    shape: singleQuote('round'),
    value: DEFAULT_FALSE,
    disabled: DEFAULT_FALSE,
    'label-disabled': DEFAULT_FALSE,
    'label-position': singleQuote('right'),
    'use-icon-slot': DEFAULT_FALSE,
    // 'checked-color': singleQuote('#1989fa'),
    // 'icon-size': singleQuote('20px'),
  },
  'van-checkbox-group': {
    disabled: DEFAULT_FALSE,
    max: '0',
    direction: singleQuote('vertical'),
  },
  'van-datetime-picker': {
    type: singleQuote('datetime'),
    'min-date': 'xs.datetime(xs.date(xs.year - 10, 0, 1))', // 十年前
    'max-date': 'xs.datetime(xs.date(xs.year + 10, 11, 31))', // 十年后
    'min-hour': '0',
    'max-hour': '23',
    'min-minute': '0',
    'max-minute': '59',
    'show-toolbar': DEFAULT_TRUE,
    loading: DEFAULT_FALSE,
    'item-height': '44',
    'confirm-button-text': singleQuote('确认'),
    'cancel-button-text': singleQuote('取消'),
    'visible-item-count': '6',
  },
  'van-field': {
    type: singleQuote('text'),
    fixed: DEFAULT_FALSE,
    focus: DEFAULT_FALSE,
    border: DEFAULT_TRUE,
    disabled: DEFAULT_FALSE,
    readonly: DEFAULT_FALSE,
    clearable: DEFAULT_FALSE,
    clickable: DEFAULT_FALSE,
    required: DEFAULT_FALSE,
    center: DEFAULT_FALSE,
    password: DEFAULT_FALSE,
    'title-width': singleQuote('6.2em'),
    maxlength: '-1',
    'is-link': DEFAULT_FALSE,
    'show-word-limit': DEFAULT_FALSE,
    error: DEFAULT_FALSE,
    'input-align': singleQuote('left'),
    autosize: DEFAULT_FALSE,
    'confirm-type': singleQuote('done'),
    'confirm-hold': DEFAULT_FALSE,
    'hold-keyboard': DEFAULT_FALSE,
    'cursor-spacing': '50',
    'adjust-position': DEFAULT_TRUE,
    'show-confirm-bar': DEFAULT_TRUE,
    'selection-start': '-1',
    'selection-end': '-1',
    'auto-focus': DEFAULT_FALSE,
    'disable-default-padding': DEFAULT_TRUE,
    cursor: '-1',
    'clear-trigger': singleQuote('focus'),
    'always-embed': DEFAULT_FALSE,
    'extra-event-params': DEFAULT_FALSE
  },
  'van-picker': {
    columns: DEFAULT_EMPTY_ARRAY,
    'show-toolbar': DEFAULT_FALSE,
    'toolbar-position': singleQuote('top'),
    loading: DEFAULT_FALSE,
    'value-key': singleQuote('text'),
    'item-height': '44',
    'confirm-button-text': singleQuote('确认'),
    'cancel-button-text': singleQuote('取消'),
    'visible-item-count': '6',
    'default-index': '0',
  },
  'van-radio-group': {
    disabled: DEFAULT_FALSE,
    direction: singleQuote('vertical'),
  },
  'van-radio': {
    shape: singleQuote('round'),
    disabled: DEFAULT_FALSE,
    'label-disabled': DEFAULT_FALSE,
    'label-position': singleQuote('right'),
    // 'icon-size': singleQuote('20px'),
    // 'checked-color': singleQuote('#1989fa'),
    'use-icon-slot': DEFAULT_FALSE,
  },
  'van-rate': {
    count: '5',
    // size: singleQuote('20px'),
    // gutter: singleQuote('4px'),
    // color: singleQuote('#ffd21e'),
    // 'void-color': singleQuote('#c7c7c7'),
    icon: singleQuote('star'),
    'void-icon': singleQuote('star-o'),
    'allow-half': DEFAULT_FALSE,
    readonly: DEFAULT_FALSE,
    disabled: DEFAULT_FALSE,
    // 'disabled-color': singleQuote('#bdbdbd'),
    touchable: DEFAULT_TRUE,
  },
  'van-search': {
    shape: singleQuote('square'),
    // background: singleQuote('#f2f2f2'),
    'show-action': DEFAULT_FALSE,
    'action-text': singleQuote('取消'),
    focus: DEFAULT_FALSE,
    error: DEFAULT_FALSE,
    disabled: DEFAULT_FALSE,
    readonly: DEFAULT_FALSE,
    clearable: DEFAULT_TRUE,
    'clear-trigger': singleQuote('focus'),
    'clear-icon': singleQuote('clear'),
    maxlength: '-1',
    'use-action-slot': DEFAULT_FALSE,
    'input-align': singleQuote('left'),
    'use-left-icon-slot': DEFAULT_FALSE,
    'use-right-icon-slot': DEFAULT_FALSE,
    'left-icon': singleQuote('search'),
    'cursor-spacing': '0'
  },
  'van-slider': {
    value: '0',
    disabled: DEFAULT_FALSE,
    max: '100',
    min: '0',
    step: '1',
    // 'bar-height': singleQuote('2px'),
    // 'active-color': singleQuote('#1989fa'),
    // 'inactive-color': singleQuote('#e5e5e5'),
    'use-slot-button': DEFAULT_FALSE,
    range: DEFAULT_FALSE,
    vertical: DEFAULT_FALSE,
  },
  'van-stepper': {
    // value: '最小值',
    min: '1',
    step: '1',
    integer: DEFAULT_FALSE,
    disabled: DEFAULT_FALSE,
    'disable-input': DEFAULT_FALSE,
    'async-change': DEFAULT_FALSE,
    // 'input-width': singleQuote('32px'),
    // 'button-size': singleQuote('28px'),
    'show-plus': DEFAULT_TRUE,
    'show-minus': DEFAULT_TRUE,
    'long-press': DEFAULT_TRUE,
    'always-embed': DEFAULT_FALSE,
  },
  'van-switch': {
    checked: DEFAULT_FALSE,
    loading: DEFAULT_FALSE,
    disabled: DEFAULT_FALSE,
    // size: singleQuote('30px'),
    // 'active-color': singleQuote('#1989fa'),
    // 'inactive-color': singleQuote('#fff'),
    'active-value': DEFAULT_TRUE,
    'inactive-value': DEFAULT_FALSE,
  },
  'van-uploader': {
    accept: singleQuote('image'),
    sizeType: "['original','compressed']",
    // 'preview-size': singleQuote('80px'),
    'preview-image': DEFAULT_TRUE,
    'preview-full-image': DEFAULT_TRUE,
    multiple: DEFAULT_FALSE,
    disabled: DEFAULT_FALSE,
    'show-upload': DEFAULT_TRUE,
    deletable: DEFAULT_TRUE,
    capture: "['album','camera']",
    'image-fit': singleQuote('scaleToFill'),
    'upload-icon': singleQuote('plus'),
    'max-duration': '60',
    'media-type': "['image','video']",
    showmenu: DEFAULT_TRUE,
    'video-fit': singleQuote('contain'),
    'preview-file': DEFAULT_TRUE,
    'referrer-policy': singleQuote('no-referrer'),
  },
  'van-action-sheet': {
    actions: DEFAULT_EMPTY_ARRAY,
    'z-index': '100',
    round: DEFAULT_TRUE,
    'close-on-click-action': DEFAULT_TRUE,
    'close-on-click-overlay': DEFAULT_TRUE,
    'safe-area-inset-bottom': DEFAULT_TRUE,
  },
  'van-dialog': {
    // width: singleQuote('320px'),
    theme: singleQuote('default'),
    'message-align': singleQuote('center'),
    'z-index': '100',
    'show-confirm-button': DEFAULT_TRUE,
    'show-cancel-button': DEFAULT_FALSE,
    'confirm-button-text': singleQuote('确认'),
    'cancel-button-text': singleQuote('取消'),
    // 'confirm-button-color': singleQuote('#ee0a24'),
    // 'cancel-button-color': singleQuote('#333'),
    overlay: DEFAULT_TRUE,
    'close-on-click-overlay': DEFAULT_FALSE,
    'use-slot': DEFAULT_FALSE,
    'use-title-slot': DEFAULT_FALSE,
    'async-close': DEFAULT_FALSE,
    transition: singleQuote('scale'),
    lang: singleQuote('en'),
    // 'send-message-title': singleQuote('当前标题'),
    // 'send-message-path': singleQuote('当前分享路径'),
    // 'send-message-img': singleQuote('截图'),
    'show-message-card': DEFAULT_FALSE,
  },
  'van-dropdown-menu': {
    // 'active-color': singleQuote('#ee0a24'),
    'z-index': '10',
    duration: '200',
    direction: singleQuote('down'),
    overlay: DEFAULT_TRUE,
    'safe-area-tab-bar': DEFAULT_FALSE,
    'close-on-click-overlay': DEFAULT_TRUE,
    'close-on-click-outside': DEFAULT_TRUE,
  },
  'van-dropdown-item': {
    // title: singleQuote('当前选中项文字'),
    options: DEFAULT_EMPTY_ARRAY,
    disabled: DEFAULT_FALSE,
    'use-before-toggle': DEFAULT_FALSE,
    'root-portal': DEFAULT_FALSE
  },
  'van-loading': {
    // color: singleQuote('#c9c9c9'),
    type: singleQuote('circular'),
    // size: singleQuote('30px'),
    // 'text-size': singleQuote('14px'),
    vertical: DEFAULT_FALSE,
  },
  'van-overlay': {
    show: DEFAULT_FALSE,
    'z-index': '1',
    duration: '0.3',
    'lock-scroll': DEFAULT_TRUE,
    'root-portal': DEFAULT_FALSE
  },
  'van-share-sheet': {
    options: DEFAULT_EMPTY_ARRAY,
    'cancel-text': singleQuote('取消'),
    duration: '300',
    overlay: DEFAULT_TRUE,
    'close-on-click-overlay': DEFAULT_TRUE,
    'safe-area-inset-bottom': DEFAULT_TRUE,
  },
  'van-swipe-cell': {
    'left-width': '0',
    'right-width': '0',
    'async-close': DEFAULT_FALSE,
    disabled: DEFAULT_FALSE,
  },
  'van-circle': {
    value: '0',
    size: '100',
    // color: singleQuote('#1989fa'),
    // 'layer-color': singleQuote('#fff'),
    speed: '50',
    'stroke-width': '4',
    clockwise: DEFAULT_TRUE,
  },
  'van-collapse': {
    accordion: DEFAULT_FALSE,
    border: DEFAULT_TRUE,
  },
  'van-collapse-item': {
    name: singleQuote('index'),
    border: DEFAULT_TRUE,
    'is-link': DEFAULT_TRUE,
    clickable: DEFAULT_FALSE,
    disabled: DEFAULT_FALSE,
  },
  'van-count-down': {
    format: singleQuote('HH:mm:ss'),
    'auto-start': DEFAULT_TRUE,
    millisecond: DEFAULT_FALSE,
    'use-slot': DEFAULT_FALSE,
  },
  'van-divider': {
    dashed: DEFAULT_FALSE,
    hairline: DEFAULT_FALSE,
  },
  'van-empty': {
    image: singleQuote('default')
  },
  'van-notice-bar': {
    // color: singleQuote('#ed6a0c'),
    // background: singleQuote('#fffbe8'),
    delay: '1',
    speed: '60',
    wrapable: DEFAULT_FALSE,
    'open-type': singleQuote('navigate'),
  },
  'van-progress': {
    inactive: DEFAULT_FALSE,
    percentage: '0',
    // 'stroke-width': singleQuote('4px'),
    'show-pivot': DEFAULT_TRUE,
    // color: singleQuote('#1989fa'),
    // 'text-color': singleQuote('#fff'),
    // 'track-color': singleQuote('#e5e5e5'),
    // 'pivot-text': singleQuote('百分比文字'),
    // 'pivot-color': singleQuote('与进度条颜色一致'),
  },
  'van-skeleton': {
    row: '0',
    'row-width': singleQuote('100%'),
    title: DEFAULT_FALSE,
    'title-width': singleQuote('40%'),
    avatar: DEFAULT_FALSE,
    // 'avatar-size': singleQuote('32px'),
    'avatar-shape': singleQuote('round'),
    loading: DEFAULT_TRUE,
    animate: DEFAULT_TRUE,
  },
  'van-steps': {
    active: '0',
    steps: DEFAULT_EMPTY_ARRAY,
    direction: singleQuote('horizontal'),
    // 'active-color': singleQuote('#07c160'),
    // 'inactive-color': singleQuote('#969799'),
    // 'active-icon': singleQuote('checked'),
  },
  'van-sticky': {
    'offset-top': '0',
    'z-index': '99',
  },
  'van-tag': {
    plain: DEFAULT_FALSE,
    round: DEFAULT_FALSE,
    mark: DEFAULT_FALSE,
    // 'text-color': singleQuote('white'),
    closeable: DEFAULT_FALSE,
  },
  'van-grid': {
    'column-num': '4',
    // 'icon-size': singleQuote('28px'),
    gutter: '0',
    border: DEFAULT_TRUE,
    center: DEFAULT_TRUE,
    square: DEFAULT_FALSE,
    clickable: DEFAULT_FALSE,
    direction: singleQuote('vertical'),
    reverse: DEFAULT_FALSE,
    'use-slot': DEFAULT_FALSE,
  },
  'van-grid-item': {
    'icon-prefix': singleQuote('van-icon'),
    dot: DEFAULT_FALSE,
    'link-type': singleQuote('navigateTo'),
  },
  'van-index-bar': {
    'index-list': singleQuote('A-Z'),
    'z-index': '1',
    sticky: DEFAULT_TRUE,
    'sticky-offset-top': '0',
    // 'highlight-color': singleQuote('#07c160'),
  },
  'van-index-anchor': {
    'use-slot': DEFAULT_FALSE,
  },
  'van-nav-bar': {
    'left-arrow': DEFAULT_FALSE,
    fixed: DEFAULT_FALSE,
    placeholder: DEFAULT_FALSE,
    border: DEFAULT_TRUE,
    'z-index': '1',
    'safe-area-inset-top': DEFAULT_TRUE,
  },
  'van-sidebar': {
    'active-key': '0',
  },
  'van-sidebar-item': {
    dot: DEFAULT_FALSE,
    disabled: DEFAULT_FALSE,
  },
  'van-tabs': {
    type: singleQuote('line'),
    // color: singleQuote('#ee0a24'),
    active: '0',
    duration: '0.3',
    'line-width': singleQuote('40px'),
    // 'line-height': singleQuote('3px'),
    animated: DEFAULT_FALSE,
    border: DEFAULT_FALSE,
    ellipsis: DEFAULT_TRUE,
    sticky: DEFAULT_FALSE,
    swipeable: DEFAULT_FALSE,
    'lazy-render': DEFAULT_TRUE,
    'swipe-threshold': '5',
    'z-index': '1',
    'use-before-change': DEFAULT_FALSE
  },
  'van-tab': {
    // name: '标签的索引值',
    disabled: DEFAULT_FALSE,
  },
  'van-tabbar': {
    fixed: DEFAULT_TRUE,
    placeholder: DEFAULT_FALSE,
    border: DEFAULT_TRUE,
    'z-index': '1',
    // 'active-color': singleQuote('#1989fa'),
    // 'inactive-color': singleQuote('#7d7e80'),
    'safe-area-inset-bottom': DEFAULT_TRUE,
  },
  'van-tabbar-item': {
    // name: '当前标签的索引值',
    'icon-prefix': singleQuote('van-icon'),
    'link-type': singleQuote('redirectTo')
  },
  'van-tree-select': {
    items: DEFAULT_EMPTY_ARRAY,
    height: '300',
    'main-active-index': '0',
    'active-id': '0',
    max: 'Infinity',
    'selected-icon': singleQuote('success'),
  },
  'van-area': {
    'columns-num': '3',
    'columns-placeholder': DEFAULT_EMPTY_ARRAY,
    loading: DEFAULT_FALSE,
    'item-height': '44',
    'visible-item-count': '6',
    'confirm-button-text': singleQuote('确认'),
    'cancel-button-text': singleQuote('取消'),
    'show-toolbar': DEFAULT_TRUE,
  },
  'van-card': {
    'thumb-mode': singleQuote('aspectFit'),
    centered: DEFAULT_FALSE,
    currency: singleQuote('¥'),
    'link-type': singleQuote('navigateTo'),
    'lazy-load': DEFAULT_FALSE,
  },
  'van-submit-bar': {
    label: singleQuote('合计：'),
    'button-type': singleQuote('danger'),
    disabled: DEFAULT_FALSE,
    loading: DEFAULT_FALSE,
    currency: singleQuote('¥'),
    'safe-area-inset-bottom': DEFAULT_TRUE,
    'decimal-length': '2',
  },
  'van-goods-action': {
    'safe-area-inset-bottom': DEFAULT_TRUE,
  },
  'van-goods-action-icon': {
    'link-type': singleQuote('navigateTo'),
    disabled: DEFAULT_FALSE,
    loading: DEFAULT_FALSE,
    lang: singleQuote('en'),
    // 'send-message-title': singleQuote('当前标题'),
    // 'send-message-path': singleQuote('当前分享路径'),
    // 'send-message-img': singleQuote('截图'),
    'show-message-card': DEFAULT_FALSE,
    'class-prefix': singleQuote('van-icon'),
  },
  'van-goods-action-button': {
    'link-type': singleQuote('navigateTo'),
    type: singleQuote('danger'),
    plain: DEFAULT_FALSE,
    size: singleQuote('normal'),
    disabled: DEFAULT_FALSE,
    loading: DEFAULT_FALSE,
    lang: singleQuote('en'),
    // 'send-message-title': singleQuote('当前标题'),
    // 'send-message-path': singleQuote('当前分享路径'),
    // 'send-message-img': singleQuote('截图'),
    'show-message-card': DEFAULT_FALSE,
  },
};
